/**
 * Makes one Google Forms quiz per chapter.
 * GENERATED by build.js from data/questions.json — do not edit google-form.gs by hand.
 *
 * How to use:
 *   1. Open https://script.google.com and make a project (one time only).
 *   2. Replace all code with this file, then run createForms().
 *   3. Run it again after new chapters are added. Chapters that already
 *      have a form are skipped, so no duplicates are made.
 *   4. The log shows the links. The links are also in the "Olympiad forms" sheet.
 *
 * To rebuild a chapter after a correction, run resetChapter("Class 3", 1),
 * then createForms() again. The old form is moved to the trash.
 */
const DATA = {
  "book": "Olympiad Class 3",
  "chapters": [
    {
      "class": "Class 3",
      "chapter": 1,
      "title": "Me and My Surroundings",
      "questions": [
        {
          "q": "While going to the school, Ajay saw that his shoe sole was peeling off. To whom should he go to repair his shoe?",
          "options": [
            "Carpenter",
            "Tailor",
            "Barber",
            "Cobbler"
          ],
          "answer": "D"
        },
        {
          "q": "The voice box helps us to speak, make sound and sing. Where is it found?",
          "options": [
            "Chest",
            "Throat",
            "Head",
            "Foot"
          ],
          "answer": "B"
        },
        {
          "q": "Which of the following organs helps to remove waste and extra fluid from our body?",
          "options": [
            "Lungs",
            "Heart",
            "Kidneys",
            "Liver"
          ],
          "answer": "C"
        },
        {
          "q": "Mr. Gupta works in a laboratory. He conducts experiments and does research to discover/invent new things. He is a ______.",
          "options": [
            "Astrologer",
            "Scientist",
            "Journalist",
            "Electrician"
          ],
          "answer": "B"
        },
        {
          "q": "Which of the following organs covers the windpipe to prevent the entry of food in windpipe while swallowing food?",
          "options": [
            "Oesophagus",
            "Epiglottis",
            "Larynx",
            "Ear"
          ],
          "answer": "B"
        },
        {
          "q": "We consume various products of milk. Which among these items is NOT obtained from milk?",
          "options": [
            "Curd",
            "Cream",
            "Butter",
            "Cereal"
          ],
          "answer": "D"
        },
        {
          "q": "Anita Kaul designs houses and buildings. She is a/an ______.",
          "options": [
            "Architect",
            "Conductor",
            "Mechanic",
            "Pilot"
          ],
          "answer": "A"
        }
      ]
    }
  ]
};

function createForms() {
  const props = PropertiesService.getScriptProperties();
  const sheet = linksSheet_();
  DATA.chapters.forEach(c => {
    const key = `${c.class}|${c.chapter}`;
    if (props.getProperty(key)) return;
    const form = buildForm_(c);
    props.setProperty(key, form.getId());
    sheet.appendRow([c.class, c.chapter, c.title, c.questions.length, form.getPublishedUrl(), form.getEditUrl()]);
    Logger.log(`${c.class} Ch ${c.chapter}: ${form.getPublishedUrl()}`);
  });
  Logger.log("Done. All links: " + sheet.getParent().getUrl());
}

function resetChapter(cls, chapter) {
  const props = PropertiesService.getScriptProperties();
  const key = `${cls}|${chapter}`;
  const id = props.getProperty(key);
  if (id) DriveApp.getFileById(id).setTrashed(true);
  props.deleteProperty(key);
}

function buildForm_(c) {
  const form = FormApp.create(`${c.class} · Chapter ${c.chapter}: ${c.title}`)
    .setDescription(`${DATA.book} · ${c.questions.length} questions`)
    .setIsQuiz(true);
  form.addTextItem().setTitle("Your name").setRequired(true);
  c.questions.forEach((q, i) => {
    const answerIndex = "ABCD".indexOf(q.answer);
    const item = form.addMultipleChoiceItem();
    item.setTitle(`${i + 1}. ${q.q}`)
      .setChoices(q.options.map((o, j) => item.createChoice(`(${"ABCD"[j]}) ${o}`, j === answerIndex)))
      .setPoints(1)
      .setRequired(true)
      .setFeedbackForIncorrect(FormApp.createFeedback()
        .setText(`The answer is (${q.answer}) ${q.options[answerIndex]}.`).build());
  });
  return form;
}

function linksSheet_() {
  const props = PropertiesService.getScriptProperties();
  let id = props.getProperty("sheetId");
  if (!id) {
    const ss = SpreadsheetApp.create("Olympiad forms");
    ss.getActiveSheet().appendRow(["Class", "Chapter", "Title", "Questions", "Share link", "Edit link"]);
    id = ss.getId();
    props.setProperty("sheetId", id);
  }
  return SpreadsheetApp.openById(id).getActiveSheet();
}
